import { requireEnvVar } from "@reasonote/lib-utils-backend";

export function getApiEnv() {
  return {
    NEXT_PUBLIC_SUPABASE_URL: requireEnvVar("NEXT_PUBLIC_SUPABASE_URL"),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: requireEnvVar(
      "NEXT_PUBLIC_SUPABASE_ANON_KEY"
    ),
    OPENAI_API_KEY: requireEnvVar("OPENAI_API_KEY"),
    REASONOTE_SUPABASE_ANON_KEY: requireEnvVar("REASONOTE_SUPABASE_ANON_KEY"),
    REASONOTE_SUPABASE_URL: requireEnvVar("REASONOTE_SUPABASE_URL"),
    STRIPE_SECRET_KEY: requireEnvVar("STRIPE_SECRET_KEY"),
    SUPABASE_SERVICE_KEY: requireEnvVar("SUPABASE_SERVICE_KEY"),
    STRIPE_WEBHOOK_SECRET: requireEnvVar("STRIPE_WEBHOOK_SECRET"),
    RSN_NOTION_CLIENT_ID: requireEnvVar("RSN_NOTION_CLIENT_ID"),
    RSN_NOTION_CLIENT_SECRET: requireEnvVar("RSN_NOTION_CLIENT_SECRET"),
    NEXT_PUBLIC_RSN_NOTION_AUTHORIZATION_URL: requireEnvVar(
      "NEXT_PUBLIC_RSN_NOTION_AUTHORIZATION_URL"
    ),
    NEXT_PUBLIC_RSN_NOTION_REDIRECT_URL: requireEnvVar(
      "NEXT_PUBLIC_RSN_NOTION_REDIRECT_URL"
    ),
  };
}
