import { requireEnvVar } from "@reasonote/lib-utils-backend";

export const API_ENV = {
  NEXT_PUBLIC_SUPABASE_URL: requireEnvVar("NEXT_PUBLIC_SUPABASE_URL"),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: requireEnvVar("NEXT_PUBLIC_SUPABASE_ANON_KEY"),
  OPENAI_API_KEY: requireEnvVar("OPENAI_API_KEY"),
  REASONOTE_SUPABASE_ANON_KEY: requireEnvVar("REASONOTE_SUPABASE_ANON_KEY"),
  REASONOTE_SUPABASE_URL: requireEnvVar("REASONOTE_SUPABASE_URL"),
  STRIPE_SECRET_KEY: requireEnvVar("STRIPE_SECRET_KEY"),
  SUPABASE_SERVICE_KEY: requireEnvVar("SUPABASE_SERVICE_KEY"),
  STRIPE_WEBHOOK_SECRET: requireEnvVar("STRIPE_WEBHOOK_SECRET"),
};
