---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- View: public.user_current_licenses

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (VIEW: public.user_current_licenses)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: user_current_licenses; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.user_current_licenses AS
 WITH sysdata_licenses AS (
         SELECT rsn_user_sysdata.auth_id,
            jsonb_each(COALESCE(rsn_user_sysdata.extra_license_info, '{}'::jsonb)) AS license_info
           FROM public.rsn_user_sysdata
        )
 SELECT sysdata_licenses.auth_id,
    (sysdata_licenses.license_info).key AS license_type,
    'sysdata'::text AS source
   FROM sysdata_licenses
  WHERE (((sysdata_licenses.license_info).value)::boolean = true)
UNION ALL
 SELECT auth.id AS auth_id,
    s.stripe_product_lookup_key AS license_type,
    'stripe'::text AS source
   FROM (public.get_user_stripe_subs_short() s(stripe_subscription_id, stripe_product_id, stripe_product_name, stripe_product_lookup_key, current_period_start, current_period_end, status, canceled_at, cancellation_reason)
     CROSS JOIN auth.users auth)
  WHERE (auth.id = auth.uid());


ALTER TABLE public.user_current_licenses OWNER TO postgres;

--
-- Name: TABLE user_current_licenses; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.user_current_licenses TO anon;
GRANT ALL ON TABLE public.user_current_licenses TO authenticated;
GRANT ALL ON TABLE public.user_current_licenses TO service_role;


--
-- PostgreSQL database dump complete
--


------------------------------
-- END: PG_DUMP RESULT (VIEW: public.user_current_licenses)
---------------------------------------------------------------------------
