---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- View: public.vw_entity_vec_permissions

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (VIEW: public.vw_entity_vec_permissions)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vw_entity_vec_permissions; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_entity_vec_permissions AS
 SELECT 'goal'::text AS tablename,
    vw_goal_memauth.goal_id AS entity_id,
    vw_goal_memauth.principal_id,
    vw_goal_memauth.principal_type,
    vw_goal_memauth.permissions,
    vw_goal_memauth.is_public
   FROM public.vw_goal_memauth
UNION ALL
 SELECT 'skill'::text AS tablename,
    vw_skill_memauth.skill_id AS entity_id,
    vw_skill_memauth.principal_id,
    vw_skill_memauth.principal_type,
    vw_skill_memauth.permissions,
    vw_skill_memauth.is_public
   FROM public.vw_skill_memauth
UNION ALL
 SELECT 'rsn_page'::text AS tablename,
    vw_rsn_page_memauth.page_id AS entity_id,
    vw_rsn_page_memauth.principal_id,
    vw_rsn_page_memauth.principal_type,
    vw_rsn_page_memauth.permissions,
    vw_rsn_page_memauth.is_public
   FROM public.vw_rsn_page_memauth
UNION ALL
 SELECT 'snip'::text AS tablename,
    vw_snip_memauth.snip_id AS entity_id,
    vw_snip_memauth.principal_id,
    vw_snip_memauth.principal_type,
    vw_snip_memauth.permissions,
    vw_snip_memauth.is_public
   FROM public.vw_snip_memauth;


ALTER TABLE public.vw_entity_vec_permissions OWNER TO postgres;

--
-- Name: VIEW vw_entity_vec_permissions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON VIEW public.vw_entity_vec_permissions IS 'Consolidated permissions view for all vectorizable entities';


--
-- Name: TABLE vw_entity_vec_permissions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.vw_entity_vec_permissions TO anon;
GRANT ALL ON TABLE public.vw_entity_vec_permissions TO authenticated;
GRANT ALL ON TABLE public.vw_entity_vec_permissions TO service_role;


--
-- PostgreSQL database dump complete
--


------------------------------
-- END: PG_DUMP RESULT (VIEW: public.vw_entity_vec_permissions)
---------------------------------------------------------------------------
