---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- View: public.vw_entity_permissions

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (VIEW: public.vw_entity_permissions)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vw_entity_permissions; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_entity_permissions AS
 SELECT ma.resource_entity_type AS entity_type,
    ma.resource_entity_id AS entity_id,
    ma.principal_id,
    ma.is_public,
    array_agg(alp.permission_code ORDER BY alp.permission_code) AS permissions
   FROM (public.memauth ma
     JOIN public.access_level_permission alp ON ((((alp.entity_type)::text = ma.resource_entity_type) AND (upper((alp.access_level)::text) = upper((ma.access_level)::text)))))
  GROUP BY ma.resource_entity_type, ma.resource_entity_id, ma.principal_id, ma.is_public;


ALTER TABLE public.vw_entity_permissions OWNER TO postgres;

--
-- Name: VIEW vw_entity_permissions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON VIEW public.vw_entity_permissions IS 'Aggregated permissions for each entity and principal/public.';


--
-- Name: TABLE vw_entity_permissions; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.vw_entity_permissions TO anon;
GRANT ALL ON TABLE public.vw_entity_permissions TO authenticated;
GRANT ALL ON TABLE public.vw_entity_permissions TO service_role;


--
-- PostgreSQL database dump complete
--


------------------------------
-- END: PG_DUMP RESULT (VIEW: public.vw_entity_permissions)
---------------------------------------------------------------------------
