---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- View: public.vw_skill_memauth

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (VIEW: public.vw_skill_memauth)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vw_skill_memauth; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_skill_memauth AS
 SELECT s.id AS skill_id,
    s.created_by AS principal_id,
    'user'::public.agent_type AS principal_type,
    ARRAY['skill.SELECT'::text, 'skill.INSERT'::text, 'skill.UPDATE'::text, 'skill.DELETE'::text] AS permissions,
    false AS is_public
   FROM public.skill s
UNION ALL
 SELECT s.id AS skill_id,
    'anonymous'::character varying AS principal_id,
    'user'::public.agent_type AS principal_type,
    ARRAY[]::text[] AS permissions,
    false AS is_public
   FROM public.skill s
  WHERE public.is_admin();


ALTER TABLE public.vw_skill_memauth OWNER TO postgres;

--
-- Name: VIEW vw_skill_memauth; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON VIEW public.vw_skill_memauth IS 'Shows permissions for skills - currently only the creator has permissions';


--
-- Name: TABLE vw_skill_memauth; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.vw_skill_memauth TO anon;
GRANT ALL ON TABLE public.vw_skill_memauth TO authenticated;
GRANT ALL ON TABLE public.vw_skill_memauth TO service_role;


--
-- PostgreSQL database dump complete
--


------------------------------
-- END: PG_DUMP RESULT (VIEW: public.vw_skill_memauth)
---------------------------------------------------------------------------
