---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Table: public.access_level_permission

---------------------------------------------------------------------------
-- BEGIN: TABLE DESCRIPTION (TABLE: public.access_level_permission)
------------------------------
--                                  Table "public.access_level_permission"
--      Column      |            Type             | Collation | Nullable |             Default              
-- -----------------+-----------------------------+-----------+----------+----------------------------------
--  entity_type     | character varying(512)      |           | not null | 
--  access_level    | character varying(512)      |           | not null | 
--  permission_code | character varying(512)      |           | not null | 
--  created_by      | text                        |           |          | current_rsn_user_id()
--  created_date    | timestamp without time zone |           | not null | (now() AT TIME ZONE 'utc'::text)
--  updated_by      | text                        |           |          | current_rsn_user_id()
--  updated_date    | timestamp without time zone |           | not null | (now() AT TIME ZONE 'utc'::text)
-- Indexes:
--     "access_level_permission_pkey" PRIMARY KEY, btree (entity_type, access_level, permission_code)
--     "idx_access_level_permission_lesson" btree (entity_type, access_level, permission_code) WHERE entity_type::text = 'lesson'::text
--     "idx_alp_activity_access" btree (entity_type, upper(access_level::text))
--     "idx_alp_activity_access_no_upper" btree (entity_type, access_level)
-- Foreign-key constraints:
--     "entity_type_access_level_fkey" FOREIGN KEY (access_level, entity_type) REFERENCES entity_type_access_level(access_level, entity_type)
--     "permission_code_fkey" FOREIGN KEY (permission_code) REFERENCES permission(permission_code)
-- Policies:
--     POLICY "access_level_permission DELETE" FOR DELETE
--       USING (false)
--     POLICY "access_level_permission INSERT" FOR INSERT
--       WITH CHECK (false)
--     POLICY "access_level_permission SELECT" FOR SELECT
--       USING (true)
--     POLICY "access_level_permission UPDATE" FOR UPDATE
--       USING (false)
-- Triggers:
--     log_operation AFTER INSERT OR DELETE OR UPDATE ON access_level_permission FOR EACH ROW EXECUTE FUNCTION tgr_log_operation()
--     run_tgr_apply_audit BEFORE INSERT OR UPDATE ON access_level_permission FOR EACH ROW EXECUTE FUNCTION tgr_apply_audit()
-- 
-- 

------------------------------
-- END: TABLE DESCRIPTION (TABLE: public.access_level_permission)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (TABLE: public.access_level_permission)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: access_level_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.access_level_permission (
    entity_type character varying(512) NOT NULL,
    access_level character varying(512) NOT NULL,
    permission_code character varying(512) NOT NULL,
    created_by text DEFAULT public.current_rsn_user_id(),
    created_date timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    updated_by text DEFAULT public.current_rsn_user_id(),
    updated_date timestamp without time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL
);


ALTER TABLE public.access_level_permission OWNER TO postgres;

--
-- Name: TABLE access_level_permission; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.access_level_permission IS 'Associates access levels with the specific permissions they confer.';


--
-- Name: access_level_permission access_level_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.access_level_permission
    ADD CONSTRAINT access_level_permission_pkey PRIMARY KEY (entity_type, access_level, permission_code);


--
-- Name: idx_access_level_permission_lesson; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_access_level_permission_lesson ON public.access_level_permission USING btree (entity_type, access_level, permission_code) WHERE ((entity_type)::text = 'lesson'::text);


--
-- Name: idx_alp_activity_access; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alp_activity_access ON public.access_level_permission USING btree (entity_type, upper((access_level)::text));


--
-- Name: idx_alp_activity_access_no_upper; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_alp_activity_access_no_upper ON public.access_level_permission USING btree (entity_type, access_level);


--
-- Name: access_level_permission log_operation; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER log_operation AFTER INSERT OR DELETE OR UPDATE ON public.access_level_permission FOR EACH ROW EXECUTE FUNCTION public.tgr_log_operation();


--
-- Name: access_level_permission run_tgr_apply_audit; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER run_tgr_apply_audit BEFORE INSERT OR UPDATE ON public.access_level_permission FOR EACH ROW EXECUTE FUNCTION public.tgr_apply_audit();


--
-- Name: access_level_permission entity_type_access_level_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.access_level_permission
    ADD CONSTRAINT entity_type_access_level_fkey FOREIGN KEY (access_level, entity_type) REFERENCES public.entity_type_access_level(access_level, entity_type);


--
-- Name: access_level_permission permission_code_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.access_level_permission
    ADD CONSTRAINT permission_code_fkey FOREIGN KEY (permission_code) REFERENCES public.permission(permission_code);


--
-- Name: access_level_permission; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.access_level_permission ENABLE ROW LEVEL SECURITY;

--
-- Name: access_level_permission access_level_permission DELETE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "access_level_permission DELETE" ON public.access_level_permission FOR DELETE USING (false);


--
-- Name: access_level_permission access_level_permission INSERT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "access_level_permission INSERT" ON public.access_level_permission FOR INSERT WITH CHECK (false);


--
-- Name: access_level_permission access_level_permission SELECT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "access_level_permission SELECT" ON public.access_level_permission FOR SELECT USING (true);


--
-- Name: access_level_permission access_level_permission UPDATE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "access_level_permission UPDATE" ON public.access_level_permission FOR UPDATE USING (false);


--
-- Name: TABLE access_level_permission; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.access_level_permission TO anon;
GRANT ALL ON TABLE public.access_level_permission TO authenticated;
GRANT ALL ON TABLE public.access_level_permission TO service_role;


--
-- PostgreSQL database dump complete
--



------------------------------
-- END: PG_DUMP RESULT (TABLE: public.access_level_permission)
---------------------------------------------------------------------------

