---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Table: public.activity_set_activity

---------------------------------------------------------------------------
-- BEGIN: TABLE DESCRIPTION (TABLE: public.activity_set_activity)
------------------------------
--                                   Table "public.activity_set_activity"
--     Column    |           Type           | Collation | Nullable |                Default                 
-- --------------+--------------------------+-----------+----------+----------------------------------------
--  id           | text                     |           | not null | generate_typed_uuid('actsetact'::text)
--  activity_set | text                     |           |          | 
--  activity     | text                     |           |          | 
--  metadata     | jsonb                    |           |          | 
--  created_date | timestamp with time zone |           | not null | now()
--  updated_date | timestamp with time zone |           | not null | now()
--  created_by   | text                     |           |          | 
--  updated_by   | text                     |           |          | 
-- Indexes:
--     "activity_set_activity_pkey" PRIMARY KEY, btree (id)
-- Check constraints:
--     "activity_set_activity_id_check" CHECK (is_valid_typed_uuid('actsetact'::text, id::typed_uuid))
-- Foreign-key constraints:
--     "activity_set_activity_activity_fkey" FOREIGN KEY (activity) REFERENCES activity(id) ON DELETE CASCADE
--     "activity_set_activity_activity_set_fkey" FOREIGN KEY (activity_set) REFERENCES activity_set(id) ON DELETE CASCADE
--     "activity_set_activity_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     "activity_set_activity_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
-- Policies:
--     POLICY "activity_set_activity DELETE" FOR DELETE
--       USING (true)
--     POLICY "activity_set_activity INSERT" FOR INSERT
--       WITH CHECK (true)
--     POLICY "activity_set_activity SELECT" FOR SELECT
--       USING (true)
--     POLICY "activity_set_activity UPDATE" FOR UPDATE
--       USING (true)
-- Triggers:
--     log_operation AFTER INSERT OR DELETE OR UPDATE ON activity_set_activity FOR EACH ROW EXECUTE FUNCTION tgr_log_operation()
--     run_tgr_apply_audit BEFORE INSERT OR UPDATE ON activity_set_activity FOR EACH ROW EXECUTE FUNCTION tgr_apply_audit()
-- 
-- 

------------------------------
-- END: TABLE DESCRIPTION (TABLE: public.activity_set_activity)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (TABLE: public.activity_set_activity)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_set_activity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.activity_set_activity (
    id text DEFAULT public.generate_typed_uuid('actsetact'::text) NOT NULL,
    activity_set text,
    activity text,
    metadata jsonb,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by text,
    updated_by text,
    CONSTRAINT activity_set_activity_id_check CHECK (public.is_valid_typed_uuid('actsetact'::text, (id)::public.typed_uuid))
);


ALTER TABLE public.activity_set_activity OWNER TO postgres;

--
-- Name: TABLE activity_set_activity; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.activity_set_activity IS 'The link between an activity set and an activity.';


--
-- Name: COLUMN activity_set_activity.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.activity_set_activity.id IS 'The unique identifier for the activity set activity.';


--
-- Name: COLUMN activity_set_activity.activity_set; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.activity_set_activity.activity_set IS 'The corresponding set.';


--
-- Name: COLUMN activity_set_activity.activity; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.activity_set_activity.activity IS 'The activity.';


--
-- Name: COLUMN activity_set_activity.metadata; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.activity_set_activity.metadata IS 'The metadata for the activity set activity.';


--
-- Name: COLUMN activity_set_activity.created_date; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.activity_set_activity.created_date IS 'The date that this activity set activity was created.';


--
-- Name: COLUMN activity_set_activity.updated_date; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.activity_set_activity.updated_date IS 'The date that this activity set activity was last updated.';


--
-- Name: COLUMN activity_set_activity.created_by; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.activity_set_activity.created_by IS 'The user that created this activity set activity.';


--
-- Name: COLUMN activity_set_activity.updated_by; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.activity_set_activity.updated_by IS 'The user that last updated this activity set activity.';


--
-- Name: activity_set_activity activity_set_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_set_activity
    ADD CONSTRAINT activity_set_activity_pkey PRIMARY KEY (id);


--
-- Name: activity_set_activity log_operation; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER log_operation AFTER INSERT OR DELETE OR UPDATE ON public.activity_set_activity FOR EACH ROW EXECUTE FUNCTION public.tgr_log_operation();


--
-- Name: activity_set_activity run_tgr_apply_audit; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER run_tgr_apply_audit BEFORE INSERT OR UPDATE ON public.activity_set_activity FOR EACH ROW EXECUTE FUNCTION public.tgr_apply_audit();


--
-- Name: activity_set_activity activity_set_activity_activity_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_set_activity
    ADD CONSTRAINT activity_set_activity_activity_fkey FOREIGN KEY (activity) REFERENCES public.activity(id) ON DELETE CASCADE;


--
-- Name: activity_set_activity activity_set_activity_activity_set_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_set_activity
    ADD CONSTRAINT activity_set_activity_activity_set_fkey FOREIGN KEY (activity_set) REFERENCES public.activity_set(id) ON DELETE CASCADE;


--
-- Name: activity_set_activity activity_set_activity_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_set_activity
    ADD CONSTRAINT activity_set_activity_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.rsn_user(id) ON DELETE SET NULL;


--
-- Name: activity_set_activity activity_set_activity_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.activity_set_activity
    ADD CONSTRAINT activity_set_activity_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.rsn_user(id) ON DELETE SET NULL;


--
-- Name: activity_set_activity; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.activity_set_activity ENABLE ROW LEVEL SECURITY;

--
-- Name: activity_set_activity activity_set_activity DELETE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "activity_set_activity DELETE" ON public.activity_set_activity FOR DELETE USING (true);


--
-- Name: activity_set_activity activity_set_activity INSERT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "activity_set_activity INSERT" ON public.activity_set_activity FOR INSERT WITH CHECK (true);


--
-- Name: activity_set_activity activity_set_activity SELECT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "activity_set_activity SELECT" ON public.activity_set_activity FOR SELECT USING (true);


--
-- Name: activity_set_activity activity_set_activity UPDATE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "activity_set_activity UPDATE" ON public.activity_set_activity FOR UPDATE USING (true);


--
-- Name: TABLE activity_set_activity; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.activity_set_activity TO anon;
GRANT ALL ON TABLE public.activity_set_activity TO authenticated;
GRANT ALL ON TABLE public.activity_set_activity TO service_role;


--
-- PostgreSQL database dump complete
--



------------------------------
-- END: PG_DUMP RESULT (TABLE: public.activity_set_activity)
---------------------------------------------------------------------------

