---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Table: public.highlight

---------------------------------------------------------------------------
-- BEGIN: TABLE DESCRIPTION (TABLE: public.highlight)
------------------------------
--                                            Table "public.highlight"
--         Column         |           Type           | Collation | Nullable |              Default               
-- -----------------------+--------------------------+-----------+----------+------------------------------------
--  id                    | text                     |           | not null | generate_typed_uuid('hlght'::text)
--  content               | text                     |           | not null | 
--  note                  | text                     |           |          | 
--  location              | text                     |           |          | 
--  highlighted_at        | timestamp with time zone |           |          | 
--  tags                  | text[]                   |           |          | 
--  target_url            | text                     |           |          | 
--  target_snip_id        | text                     |           |          | 
--  target_rsn_page_id    | text                     |           |          | 
--  source_integration_id | text                     |           | not null | 
--  source_external_id    | text                     |           |          | 
--  source_metadata       | jsonb                    |           |          | 
--  created_date          | timestamp with time zone |           | not null | now()
--  updated_date          | timestamp with time zone |           | not null | now()
--  created_by            | text                     |           |          | 
--  updated_by            | text                     |           |          | 
-- Indexes:
--     "highlight_pkey" PRIMARY KEY, btree (id)
--     "highlight_source_external_id_unique" UNIQUE CONSTRAINT, btree (source_integration_id, source_external_id)
-- Check constraints:
--     "highlight__id__check_prefix" CHECK (is_valid_typed_uuid('hlght'::text, id::typed_uuid))
--     "highlight_target_check" CHECK (((target_url IS NOT NULL)::integer + (target_snip_id IS NOT NULL)::integer + (target_rsn_page_id IS NOT NULL)::integer) <= 1)
-- Foreign-key constraints:
--     "highlight_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     "highlight_source_integration_id_fkey" FOREIGN KEY (source_integration_id) REFERENCES integration(id) ON DELETE CASCADE
--     "highlight_target_rsn_page_id_fkey" FOREIGN KEY (target_rsn_page_id) REFERENCES rsn_page(id) ON DELETE CASCADE
--     "highlight_target_snip_id_fkey" FOREIGN KEY (target_snip_id) REFERENCES snip(id) ON DELETE CASCADE
--     "highlight_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
-- Policies:
--     POLICY "highlight DELETE" FOR DELETE
--       USING (((( SELECT integration.for_user
--    FROM integration
--   WHERE (integration.id = highlight.source_integration_id)) = (current_rsn_user_id())::text) OR ((target_snip_id IS NOT NULL) AND (EXISTS ( SELECT 1
--    FROM snip
--   WHERE ((snip.id = highlight.target_snip_id) AND (snip._owner = (current_rsn_user_id())::text))))) OR ((target_rsn_page_id IS NOT NULL) AND (EXISTS ( SELECT 1
--    FROM rsn_page
--   WHERE ((rsn_page.id = highlight.target_rsn_page_id) AND (rsn_page.created_by = (current_rsn_user_id())::text))))) OR (created_by = (current_rsn_user_id())::text)))
--     POLICY "highlight INSERT" FOR INSERT
--       WITH CHECK ((( SELECT integration.for_user
--    FROM integration
--   WHERE (integration.id = highlight.source_integration_id)) = (current_rsn_user_id())::text))
--     POLICY "highlight SELECT" FOR SELECT
--       USING (((( SELECT integration.for_user
--    FROM integration
--   WHERE (integration.id = highlight.source_integration_id)) = (current_rsn_user_id())::text) OR ((target_snip_id IS NOT NULL) AND (EXISTS ( SELECT 1
--    FROM snip
--   WHERE ((snip.id = highlight.target_snip_id) AND (snip._owner = (current_rsn_user_id())::text))))) OR ((target_rsn_page_id IS NOT NULL) AND (EXISTS ( SELECT 1
--    FROM rsn_page
--   WHERE ((rsn_page.id = highlight.target_rsn_page_id) AND (rsn_page.created_by = (current_rsn_user_id())::text))))) OR (created_by = (current_rsn_user_id())::text)))
--     POLICY "highlight UPDATE" FOR UPDATE
--       USING (((( SELECT integration.for_user
--    FROM integration
--   WHERE (integration.id = highlight.source_integration_id)) = (current_rsn_user_id())::text) OR ((target_snip_id IS NOT NULL) AND (EXISTS ( SELECT 1
--    FROM snip
--   WHERE ((snip.id = highlight.target_snip_id) AND (snip._owner = (current_rsn_user_id())::text))))) OR ((target_rsn_page_id IS NOT NULL) AND (EXISTS ( SELECT 1
--    FROM rsn_page
--   WHERE ((rsn_page.id = highlight.target_rsn_page_id) AND (rsn_page.created_by = (current_rsn_user_id())::text))))) OR (created_by = (current_rsn_user_id())::text)))
-- Triggers:
--     log_operation AFTER INSERT OR DELETE OR UPDATE ON highlight FOR EACH ROW EXECUTE FUNCTION tgr_log_operation()
--     run_tgr_apply_audit BEFORE INSERT OR UPDATE ON highlight FOR EACH ROW EXECUTE FUNCTION tgr_apply_audit()
-- 
-- 

------------------------------
-- END: TABLE DESCRIPTION (TABLE: public.highlight)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (TABLE: public.highlight)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: highlight; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.highlight (
    id text DEFAULT public.generate_typed_uuid('hlght'::text) NOT NULL,
    content text NOT NULL,
    note text,
    location text,
    highlighted_at timestamp with time zone,
    tags text[],
    target_url text,
    target_snip_id text,
    target_rsn_page_id text,
    source_integration_id text NOT NULL,
    source_external_id text,
    source_metadata jsonb,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by text,
    updated_by text,
    CONSTRAINT highlight__id__check_prefix CHECK (public.is_valid_typed_uuid('hlght'::text, (id)::public.typed_uuid)),
    CONSTRAINT highlight_target_check CHECK ((((((target_url IS NOT NULL))::integer + ((target_snip_id IS NOT NULL))::integer) + ((target_rsn_page_id IS NOT NULL))::integer) <= 1))
);


ALTER TABLE public.highlight OWNER TO postgres;

--
-- Name: TABLE highlight; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.highlight IS 'Highlights synced from external providers like Readwise, with optional targets in Reasonote';


--
-- Name: COLUMN highlight.content; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.content IS 'The highlighted text content';


--
-- Name: COLUMN highlight.note; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.note IS 'User note or annotation on the highlight';


--
-- Name: COLUMN highlight.location; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.location IS 'Location within source (page number, chapter, etc.)';


--
-- Name: COLUMN highlight.highlighted_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.highlighted_at IS 'When the highlight was originally created';


--
-- Name: COLUMN highlight.tags; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.tags IS 'User-defined tags for organization and filtering';


--
-- Name: COLUMN highlight.target_url; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.target_url IS 'URL target for the highlight';


--
-- Name: COLUMN highlight.target_snip_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.target_snip_id IS 'Snip target for the highlight';


--
-- Name: COLUMN highlight.target_rsn_page_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.target_rsn_page_id IS 'Page target for the highlight';


--
-- Name: COLUMN highlight.source_integration_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.source_integration_id IS 'Integration that provided this highlight';


--
-- Name: COLUMN highlight.source_external_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.source_external_id IS 'Provider-specific ID for deduplication';


--
-- Name: COLUMN highlight.source_metadata; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.highlight.source_metadata IS 'Provider metadata (book title, author, etc.)';


--
-- Name: highlight highlight_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.highlight
    ADD CONSTRAINT highlight_pkey PRIMARY KEY (id);


--
-- Name: highlight highlight_source_external_id_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.highlight
    ADD CONSTRAINT highlight_source_external_id_unique UNIQUE (source_integration_id, source_external_id);


--
-- Name: highlight log_operation; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER log_operation AFTER INSERT OR DELETE OR UPDATE ON public.highlight FOR EACH ROW EXECUTE FUNCTION public.tgr_log_operation();


--
-- Name: highlight run_tgr_apply_audit; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER run_tgr_apply_audit BEFORE INSERT OR UPDATE ON public.highlight FOR EACH ROW EXECUTE FUNCTION public.tgr_apply_audit();


--
-- Name: highlight highlight_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.highlight
    ADD CONSTRAINT highlight_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.rsn_user(id) ON DELETE SET NULL;


--
-- Name: highlight highlight_source_integration_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.highlight
    ADD CONSTRAINT highlight_source_integration_id_fkey FOREIGN KEY (source_integration_id) REFERENCES public.integration(id) ON DELETE CASCADE;


--
-- Name: highlight highlight_target_rsn_page_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.highlight
    ADD CONSTRAINT highlight_target_rsn_page_id_fkey FOREIGN KEY (target_rsn_page_id) REFERENCES public.rsn_page(id) ON DELETE CASCADE;


--
-- Name: highlight highlight_target_snip_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.highlight
    ADD CONSTRAINT highlight_target_snip_id_fkey FOREIGN KEY (target_snip_id) REFERENCES public.snip(id) ON DELETE CASCADE;


--
-- Name: highlight highlight_updated_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.highlight
    ADD CONSTRAINT highlight_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.rsn_user(id) ON DELETE SET NULL;


--
-- Name: highlight; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.highlight ENABLE ROW LEVEL SECURITY;

--
-- Name: highlight highlight DELETE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "highlight DELETE" ON public.highlight FOR DELETE USING (((( SELECT integration.for_user
   FROM public.integration
  WHERE (integration.id = highlight.source_integration_id)) = (public.current_rsn_user_id())::text) OR ((target_snip_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM public.snip
  WHERE ((snip.id = highlight.target_snip_id) AND (snip._owner = (public.current_rsn_user_id())::text))))) OR ((target_rsn_page_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM public.rsn_page
  WHERE ((rsn_page.id = highlight.target_rsn_page_id) AND (rsn_page.created_by = (public.current_rsn_user_id())::text))))) OR (created_by = (public.current_rsn_user_id())::text)));


--
-- Name: highlight highlight INSERT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "highlight INSERT" ON public.highlight FOR INSERT WITH CHECK ((( SELECT integration.for_user
   FROM public.integration
  WHERE (integration.id = highlight.source_integration_id)) = (public.current_rsn_user_id())::text));


--
-- Name: highlight highlight SELECT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "highlight SELECT" ON public.highlight FOR SELECT USING (((( SELECT integration.for_user
   FROM public.integration
  WHERE (integration.id = highlight.source_integration_id)) = (public.current_rsn_user_id())::text) OR ((target_snip_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM public.snip
  WHERE ((snip.id = highlight.target_snip_id) AND (snip._owner = (public.current_rsn_user_id())::text))))) OR ((target_rsn_page_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM public.rsn_page
  WHERE ((rsn_page.id = highlight.target_rsn_page_id) AND (rsn_page.created_by = (public.current_rsn_user_id())::text))))) OR (created_by = (public.current_rsn_user_id())::text)));


--
-- Name: highlight highlight UPDATE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "highlight UPDATE" ON public.highlight FOR UPDATE USING (((( SELECT integration.for_user
   FROM public.integration
  WHERE (integration.id = highlight.source_integration_id)) = (public.current_rsn_user_id())::text) OR ((target_snip_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM public.snip
  WHERE ((snip.id = highlight.target_snip_id) AND (snip._owner = (public.current_rsn_user_id())::text))))) OR ((target_rsn_page_id IS NOT NULL) AND (EXISTS ( SELECT 1
   FROM public.rsn_page
  WHERE ((rsn_page.id = highlight.target_rsn_page_id) AND (rsn_page.created_by = (public.current_rsn_user_id())::text))))) OR (created_by = (public.current_rsn_user_id())::text)));


--
-- Name: TABLE highlight; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.highlight TO anon;
GRANT ALL ON TABLE public.highlight TO authenticated;
GRANT ALL ON TABLE public.highlight TO service_role;


--
-- PostgreSQL database dump complete
--



------------------------------
-- END: PG_DUMP RESULT (TABLE: public.highlight)
---------------------------------------------------------------------------

