---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Table: public.reference

---------------------------------------------------------------------------
-- BEGIN: TABLE DESCRIPTION (TABLE: public.reference)
------------------------------
--                                      Table "public.reference"
--     Column    |           Type           | Collation | Nullable |             Default              
-- --------------+--------------------------+-----------+----------+----------------------------------
--  id           | text                     |           | not null | generate_typed_uuid('ref'::text)
--  raw_content  | text                     |           | not null | 
--  is_exact     | boolean                  |           | not null | false
--  rsn_vec_id   | text                     |           | not null | 
--  _ref_id      | text                     |           | not null | 
--  created_date | timestamp with time zone |           | not null | now()
--  updated_date | timestamp with time zone |           | not null | now()
--  created_by   | text                     |           |          | 
--  updated_by   | text                     |           |          | 
-- Indexes:
--     "references_pkey" PRIMARY KEY, btree (id)
-- Check constraints:
--     "references__id__check_prefix" CHECK (is_valid_typed_uuid('ref'::text, id::typed_uuid))
-- Foreign-key constraints:
--     "reference_rsn_vec_id_fkey" FOREIGN KEY (rsn_vec_id) REFERENCES rsn_vec(id) ON DELETE SET NULL
-- Policies:
--     POLICY "reference DELETE" FOR DELETE
--       USING (true)
--     POLICY "reference INSERT" FOR INSERT
--       WITH CHECK (true)
--     POLICY "reference SELECT" FOR SELECT
--       USING (true)
--     POLICY "reference UPDATE" FOR UPDATE
--       USING (true)
-- Triggers:
--     run_tgr_apply_audit BEFORE INSERT OR UPDATE ON reference FOR EACH ROW EXECUTE FUNCTION tgr_apply_audit()
-- 
-- 

------------------------------
-- END: TABLE DESCRIPTION (TABLE: public.reference)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (TABLE: public.reference)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: reference; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reference (
    id text DEFAULT public.generate_typed_uuid('ref'::text) NOT NULL,
    raw_content text NOT NULL,
    is_exact boolean DEFAULT false NOT NULL,
    rsn_vec_id text NOT NULL,
    _ref_id text NOT NULL,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by text,
    updated_by text,
    CONSTRAINT references__id__check_prefix CHECK (public.is_valid_typed_uuid('ref'::text, (id)::public.typed_uuid))
);


ALTER TABLE public.reference OWNER TO postgres;

--
-- Name: TABLE reference; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.reference IS 'Stores exact references from rsn_vecs';


--
-- Name: reference references_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reference
    ADD CONSTRAINT references_pkey PRIMARY KEY (id);


--
-- Name: reference run_tgr_apply_audit; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER run_tgr_apply_audit BEFORE INSERT OR UPDATE ON public.reference FOR EACH ROW EXECUTE FUNCTION public.tgr_apply_audit();


--
-- Name: reference reference_rsn_vec_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reference
    ADD CONSTRAINT reference_rsn_vec_id_fkey FOREIGN KEY (rsn_vec_id) REFERENCES public.rsn_vec(id) ON DELETE SET NULL;


--
-- Name: reference; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.reference ENABLE ROW LEVEL SECURITY;

--
-- Name: reference reference DELETE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "reference DELETE" ON public.reference FOR DELETE USING (true);


--
-- Name: reference reference INSERT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "reference INSERT" ON public.reference FOR INSERT WITH CHECK (true);


--
-- Name: reference reference SELECT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "reference SELECT" ON public.reference FOR SELECT USING (true);


--
-- Name: reference reference UPDATE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "reference UPDATE" ON public.reference FOR UPDATE USING (true);


--
-- Name: TABLE reference; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.reference TO anon;
GRANT ALL ON TABLE public.reference TO authenticated;
GRANT ALL ON TABLE public.reference TO service_role;


--
-- PostgreSQL database dump complete
--



------------------------------
-- END: PG_DUMP RESULT (TABLE: public.reference)
---------------------------------------------------------------------------

