---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Table: public.rsn_user

---------------------------------------------------------------------------
-- BEGIN: TABLE DESCRIPTION (TABLE: public.rsn_user)
------------------------------
--                                                       Table "public.rsn_user"
--       Column      |           Type           | Collation | Nullable |                            Default                            
-- ------------------+--------------------------+-----------+----------+---------------------------------------------------------------
--  auth_id          | uuid                     |           | not null | 
--  id               | text                     |           |          | generated always as ('rsnusr_'::text || auth_id::text) stored
--  username         | text                     |           |          | 
--  given_name       | text                     |           |          | 
--  family_name      | text                     |           |          | 
--  auth_email       | text                     |           |          | 
--  _role            | text                     |           |          | 
--  first_login_date | timestamp with time zone |           |          | 
--  last_login_date  | timestamp with time zone |           |          | 
--  timezone         | text                     |           | not null | 'UTC'::text
-- Indexes:
--     "rsn_user_pkey" PRIMARY KEY, btree (auth_id)
--     "rsn_user_id_key" UNIQUE CONSTRAINT, btree (id)
--     "rsn_user_username_key" UNIQUE CONSTRAINT, btree (username)
-- Check constraints:
--     "rsn_user__id__check_prefix" CHECK (is_valid_typed_uuid('rsnusr'::text, id::typed_uuid))
-- Foreign-key constraints:
--     "rsn_user_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) ON DELETE CASCADE
-- Referenced by:
--     TABLE "activity" CONSTRAINT "activity_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "activity" CONSTRAINT "activity_generated_for_user_fkey" FOREIGN KEY (generated_for_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "activity_set_activity" CONSTRAINT "activity_set_activity_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "activity_set_activity" CONSTRAINT "activity_set_activity_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "activity_set" CONSTRAINT "activity_set_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "activity_set" CONSTRAINT "activity_set_for_user_fkey" FOREIGN KEY (for_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "activity_set" CONSTRAINT "activity_set_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "activity_skill" CONSTRAINT "activity_skill_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "activity_skill" CONSTRAINT "activity_skill_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "activity" CONSTRAINT "activity_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "analyzer" CONSTRAINT "analyzer_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "analyzer" CONSTRAINT "analyzer_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "blog_post" CONSTRAINT "blog_post_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "blog_post" CONSTRAINT "blog_post_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "bot" CONSTRAINT "bot_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "bot_set_bot" CONSTRAINT "bot_set_bot_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "bot_set_bot" CONSTRAINT "bot_set_bot_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "bot_set" CONSTRAINT "bot_set_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "bot_set" CONSTRAINT "bot_set_for_user_fkey" FOREIGN KEY (for_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "bot_set" CONSTRAINT "bot_set_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "bot" CONSTRAINT "bot_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "chapter" CONSTRAINT "chapter_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "chapter" CONSTRAINT "chapter_for_user_fkey" FOREIGN KEY (for_user) REFERENCES rsn_user(id)
--     TABLE "chapter" CONSTRAINT "chapter_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "chat" CONSTRAINT "chat_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "chat_message" CONSTRAINT "chat_message_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "chat_message" CONSTRAINT "chat_message_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "chat" CONSTRAINT "chat_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "chrome_extension_event" CONSTRAINT "chrome_extension_event_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "chrome_extension_event" CONSTRAINT "chrome_extension_event_rsn_user_id_fkey" FOREIGN KEY (rsn_user_id) REFERENCES rsn_user(id)
--     TABLE "chrome_extension_event" CONSTRAINT "chrome_extension_event_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "course" CONSTRAINT "course_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "course" CONSTRAINT "course_for_user_fkey" FOREIGN KEY (for_user) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "course_lesson" CONSTRAINT "course_lesson_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "course_lesson" CONSTRAINT "course_lesson_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "course" CONSTRAINT "course_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "email_subscription" CONSTRAINT "email_subscription_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "email_subscription" CONSTRAINT "email_subscription_rsn_user_id_fkey" FOREIGN KEY (rsn_user_id) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "email_subscription" CONSTRAINT "email_subscription_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "entity" CONSTRAINT "entity_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "entity" CONSTRAINT "entity_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "goal" CONSTRAINT "goal_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "goal" CONSTRAINT "goal_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "integration" CONSTRAINT "integration_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "integration" CONSTRAINT "integration_for_user_fkey" FOREIGN KEY (for_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "integration_token" CONSTRAINT "integration_token_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "integration_token" CONSTRAINT "integration_token_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "integration" CONSTRAINT "integration_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "journal" CONSTRAINT "journal_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "journal" CONSTRAINT "journal_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "lesson_activity" CONSTRAINT "lesson_activity_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "lesson_activity" CONSTRAINT "lesson_activity_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "lesson" CONSTRAINT "lesson_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "lesson" CONSTRAINT "lesson_for_user_fkey" FOREIGN KEY (for_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "lesson_session" CONSTRAINT "lesson_session__user_fkey" FOREIGN KEY (_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "lesson_session" CONSTRAINT "lesson_session_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "lesson_session" CONSTRAINT "lesson_session_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "lesson" CONSTRAINT "lesson_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "memauth" CONSTRAINT "memauth_principal_user_id_fkey" FOREIGN KEY (principal_user_id) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "member_authorization" CONSTRAINT "member_authorization_user_id_fkey" FOREIGN KEY (user_id) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "notification_subscription" CONSTRAINT "notification_subscription_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "notification_subscription" CONSTRAINT "notification_subscription_rsn_user_id_fkey" FOREIGN KEY (rsn_user_id) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "notification_subscription" CONSTRAINT "notification_subscription_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "partial_skill" CONSTRAINT "partial_skill_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "partial_skill" CONSTRAINT "partial_skill_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "podcast_audio" CONSTRAINT "podcast_audio_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "podcast_audio" CONSTRAINT "podcast_audio_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "podcast" CONSTRAINT "podcast_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "podcast" CONSTRAINT "podcast_for_user_fkey" FOREIGN KEY (for_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "podcast_line" CONSTRAINT "podcast_line_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "podcast_line" CONSTRAINT "podcast_line_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "podcast_queue_item" CONSTRAINT "podcast_queue_item_for_user_fkey" FOREIGN KEY (for_user) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "podcast" CONSTRAINT "podcast_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "push_notification_subscription" CONSTRAINT "push_notification_subscription_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "push_notification_subscription" CONSTRAINT "push_notification_subscription_rsn_user_id_fkey" FOREIGN KEY (rsn_user_id) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "push_notification_subscription" CONSTRAINT "push_notification_subscription_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "resource" CONSTRAINT "resource_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "resource" CONSTRAINT "resource_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "rsn_page" CONSTRAINT "rsn_page_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "rsn_page" CONSTRAINT "rsn_page_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "rsn_page_vector" CONSTRAINT "rsn_page_vector_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "rsn_page_vector" CONSTRAINT "rsn_page_vector_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "skill" CONSTRAINT "skill_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "skill_link" CONSTRAINT "skill_link_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "skill_link" CONSTRAINT "skill_link_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "skill_set" CONSTRAINT "skill_set_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "skill_set" CONSTRAINT "skill_set_for_user_fkey" FOREIGN KEY (for_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "skill_set_skill" CONSTRAINT "skill_set_skill_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "skill_set_skill" CONSTRAINT "skill_set_skill_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "skill_set" CONSTRAINT "skill_set_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "skill" CONSTRAINT "skill_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "snip" CONSTRAINT "snip__owner_fkey" FOREIGN KEY (_owner) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "snip" CONSTRAINT "snip_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "snip" CONSTRAINT "snip_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_activity_feedback" CONSTRAINT "user_activity_feedback_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_activity_feedback" CONSTRAINT "user_activity_feedback_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_activity_result" CONSTRAINT "user_activity_result__user_fkey" FOREIGN KEY (_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_activity_result" CONSTRAINT "user_activity_result_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_activity_result" CONSTRAINT "user_activity_result_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_history" CONSTRAINT "user_history_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "user_history" CONSTRAINT "user_history_rsn_user_id_fkey" FOREIGN KEY (rsn_user_id) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "user_history" CONSTRAINT "user_history_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "user_lesson_result" CONSTRAINT "user_lesson_result__user_fkey" FOREIGN KEY (_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_lesson_result" CONSTRAINT "user_lesson_result_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_lesson_result" CONSTRAINT "user_lesson_result_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_profile" CONSTRAINT "user_profile_rsn_user_id_fkey" FOREIGN KEY (rsn_user_id) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "user_setting" CONSTRAINT "user_setting_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_setting" CONSTRAINT "user_setting_rsn_user_fkey" FOREIGN KEY (rsn_user) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "user_setting" CONSTRAINT "user_setting_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_skill" CONSTRAINT "user_skill_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_skill" CONSTRAINT "user_skill_rsn_user_fkey" FOREIGN KEY (rsn_user) REFERENCES rsn_user(id) ON DELETE CASCADE
--     TABLE "user_skill_sysdata" CONSTRAINT "user_skill_sysdata_rsn_user_fkey" FOREIGN KEY (rsn_user) REFERENCES rsn_user(id)
--     TABLE "user_skill" CONSTRAINT "user_skill_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_tour" CONSTRAINT "user_tour__user_fkey" FOREIGN KEY (_user) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_tour" CONSTRAINT "user_tour_created_by_fkey" FOREIGN KEY (created_by) REFERENCES rsn_user(id) ON DELETE SET NULL
--     TABLE "user_tour" CONSTRAINT "user_tour_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES rsn_user(id) ON DELETE SET NULL
-- Policies:
--     POLICY "rsn_user INSERT" FOR INSERT
--       WITH CHECK ((auth.uid() = auth_id))
--     POLICY "rsn_user SELECT" FOR SELECT
--       USING (true)
--     POLICY "rsn_user UPDATE" FOR UPDATE
--       USING ((auth.uid() = auth_id))
-- Triggers:
--     run_tgr_user_auth_sync BEFORE INSERT OR UPDATE ON rsn_user FOR EACH ROW EXECUTE FUNCTION tgr_user_auth_sync()
--     trigger_update_resend_synced_on_user_change AFTER UPDATE ON rsn_user FOR EACH ROW EXECUTE FUNCTION update_resend_synced_on_user_change()
-- 
-- 

------------------------------
-- END: TABLE DESCRIPTION (TABLE: public.rsn_user)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (TABLE: public.rsn_user)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: rsn_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rsn_user (
    auth_id uuid NOT NULL,
    id text GENERATED ALWAYS AS (('rsnusr_'::text || (auth_id)::text)) STORED,
    username text,
    given_name text,
    family_name text,
    auth_email text,
    _role text,
    first_login_date timestamp with time zone,
    last_login_date timestamp with time zone,
    timezone text DEFAULT 'UTC'::text NOT NULL,
    CONSTRAINT rsn_user__id__check_prefix CHECK (public.is_valid_typed_uuid('rsnusr'::text, (id)::public.typed_uuid))
);


ALTER TABLE public.rsn_user OWNER TO postgres;

--
-- Name: rsn_user rsn_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rsn_user
    ADD CONSTRAINT rsn_user_id_key UNIQUE (id);


--
-- Name: rsn_user rsn_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rsn_user
    ADD CONSTRAINT rsn_user_pkey PRIMARY KEY (auth_id);


--
-- Name: rsn_user rsn_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rsn_user
    ADD CONSTRAINT rsn_user_username_key UNIQUE (username);


--
-- Name: rsn_user run_tgr_user_auth_sync; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER run_tgr_user_auth_sync BEFORE INSERT OR UPDATE ON public.rsn_user FOR EACH ROW EXECUTE FUNCTION public.tgr_user_auth_sync();


--
-- Name: rsn_user trigger_update_resend_synced_on_user_change; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trigger_update_resend_synced_on_user_change AFTER UPDATE ON public.rsn_user FOR EACH ROW EXECUTE FUNCTION public.update_resend_synced_on_user_change();


--
-- Name: rsn_user rsn_user_auth_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rsn_user
    ADD CONSTRAINT rsn_user_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: rsn_user; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.rsn_user ENABLE ROW LEVEL SECURITY;

--
-- Name: rsn_user rsn_user INSERT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "rsn_user INSERT" ON public.rsn_user FOR INSERT WITH CHECK ((auth.uid() = auth_id));


--
-- Name: rsn_user rsn_user SELECT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "rsn_user SELECT" ON public.rsn_user FOR SELECT USING (true);


--
-- Name: rsn_user rsn_user UPDATE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "rsn_user UPDATE" ON public.rsn_user FOR UPDATE USING ((auth.uid() = auth_id));


--
-- Name: TABLE rsn_user; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.rsn_user TO anon;
GRANT ALL ON TABLE public.rsn_user TO authenticated;
GRANT ALL ON TABLE public.rsn_user TO service_role;


--
-- PostgreSQL database dump complete
--



------------------------------
-- END: PG_DUMP RESULT (TABLE: public.rsn_user)
---------------------------------------------------------------------------

