---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Table: public.rsn_vec_config

---------------------------------------------------------------------------
-- BEGIN: TABLE DESCRIPTION (TABLE: public.rsn_vec_config)
------------------------------
--                             Table "public.rsn_vec_config"
--   Column   |  Type  | Collation | Nullable |                 Default                 
-- -----------+--------+-----------+----------+-----------------------------------------
--  id        | text   |           | not null | generate_typed_uuid('rsnvecconf'::text)
--  tablename | text   |           | not null | 
--  colname   | text   |           | not null | 
--  colpath   | text[] |           |          | 
-- Indexes:
--     "rsn_vec_config_pkey" PRIMARY KEY, btree (id)
-- Check constraints:
--     "rsn_vec_index_config__id__check_prefix" CHECK (is_valid_typed_uuid('rsnvecconf'::text, id::typed_uuid))
-- Policies:
--     POLICY "rsn_vec_config__anon__delete" FOR DELETE
--       TO anon
--       USING (false)
--     POLICY "rsn_vec_config__anon__insert" FOR INSERT
--       TO anon
--       WITH CHECK (false)
--     POLICY "rsn_vec_config__anon__select" FOR SELECT
--       TO anon
--       USING (true)
--     POLICY "rsn_vec_config__anon__update" FOR UPDATE
--       TO anon
--       USING (false)
--     POLICY "rsn_vec_config__authenticated__delete" FOR DELETE
--       TO authenticated
--       USING (false)
--     POLICY "rsn_vec_config__authenticated__insert" FOR INSERT
--       TO authenticated
--       WITH CHECK (false)
--     POLICY "rsn_vec_config__authenticated__select" FOR SELECT
--       TO authenticated
--       USING (true)
--     POLICY "rsn_vec_config__authenticated__update" FOR UPDATE
--       TO authenticated
--       USING (false)
--     POLICY "rsn_vec_config__service_role__delete" FOR DELETE
--       TO service_role
--       USING (true)
--     POLICY "rsn_vec_config__service_role__insert" FOR INSERT
--       TO service_role
--       WITH CHECK (true)
--     POLICY "rsn_vec_config__service_role__select" FOR SELECT
--       TO service_role
--       USING (true)
--     POLICY "rsn_vec_config__service_role__update" FOR UPDATE
--       TO service_role
--       USING (true)
-- 
-- 

------------------------------
-- END: TABLE DESCRIPTION (TABLE: public.rsn_vec_config)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (TABLE: public.rsn_vec_config)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: rsn_vec_config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rsn_vec_config (
    id text DEFAULT public.generate_typed_uuid('rsnvecconf'::text) NOT NULL,
    tablename text NOT NULL,
    colname text NOT NULL,
    colpath text[],
    CONSTRAINT rsn_vec_index_config__id__check_prefix CHECK (public.is_valid_typed_uuid('rsnvecconf'::text, (id)::public.typed_uuid))
);


ALTER TABLE public.rsn_vec_config OWNER TO postgres;

--
-- Name: TABLE rsn_vec_config; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.rsn_vec_config IS 'Table holding configuration for vectorization.';


--
-- Name: COLUMN rsn_vec_config.tablename; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.rsn_vec_config.tablename IS 'The name of the table to be vectorized.';


--
-- Name: COLUMN rsn_vec_config.colname; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.rsn_vec_config.colname IS 'The name of the column to be vectorized.';


--
-- Name: COLUMN rsn_vec_config.colpath; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.rsn_vec_config.colpath IS 'The path within the column to be vectorized (only used for jsonb columns)';


--
-- Name: rsn_vec_config rsn_vec_config_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rsn_vec_config
    ADD CONSTRAINT rsn_vec_config_pkey PRIMARY KEY (id);


--
-- Name: rsn_vec_config; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.rsn_vec_config ENABLE ROW LEVEL SECURITY;

--
-- Name: rsn_vec_config rsn_vec_config__anon__delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__anon__delete ON public.rsn_vec_config FOR DELETE TO anon USING (false);


--
-- Name: rsn_vec_config rsn_vec_config__anon__insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__anon__insert ON public.rsn_vec_config FOR INSERT TO anon WITH CHECK (false);


--
-- Name: rsn_vec_config rsn_vec_config__anon__select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__anon__select ON public.rsn_vec_config FOR SELECT TO anon USING (true);


--
-- Name: rsn_vec_config rsn_vec_config__anon__update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__anon__update ON public.rsn_vec_config FOR UPDATE TO anon USING (false);


--
-- Name: rsn_vec_config rsn_vec_config__authenticated__delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__authenticated__delete ON public.rsn_vec_config FOR DELETE TO authenticated USING (false);


--
-- Name: rsn_vec_config rsn_vec_config__authenticated__insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__authenticated__insert ON public.rsn_vec_config FOR INSERT TO authenticated WITH CHECK (false);


--
-- Name: rsn_vec_config rsn_vec_config__authenticated__select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__authenticated__select ON public.rsn_vec_config FOR SELECT TO authenticated USING (true);


--
-- Name: rsn_vec_config rsn_vec_config__authenticated__update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__authenticated__update ON public.rsn_vec_config FOR UPDATE TO authenticated USING (false);


--
-- Name: rsn_vec_config rsn_vec_config__service_role__delete; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__service_role__delete ON public.rsn_vec_config FOR DELETE TO service_role USING (true);


--
-- Name: rsn_vec_config rsn_vec_config__service_role__insert; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__service_role__insert ON public.rsn_vec_config FOR INSERT TO service_role WITH CHECK (true);


--
-- Name: rsn_vec_config rsn_vec_config__service_role__select; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__service_role__select ON public.rsn_vec_config FOR SELECT TO service_role USING (true);


--
-- Name: rsn_vec_config rsn_vec_config__service_role__update; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY rsn_vec_config__service_role__update ON public.rsn_vec_config FOR UPDATE TO service_role USING (true);


--
-- Name: TABLE rsn_vec_config; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.rsn_vec_config TO anon;
GRANT ALL ON TABLE public.rsn_vec_config TO authenticated;
GRANT ALL ON TABLE public.rsn_vec_config TO service_role;


--
-- PostgreSQL database dump complete
--



------------------------------
-- END: PG_DUMP RESULT (TABLE: public.rsn_vec_config)
---------------------------------------------------------------------------

