---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Table: public.rsn_page_vec_queue

---------------------------------------------------------------------------
-- BEGIN: TABLE DESCRIPTION (TABLE: public.rsn_page_vec_queue)
------------------------------
--                                     Table "public.rsn_page_vec_queue"
--     Column    |           Type           | Collation | Nullable |                Default                 
-- --------------+--------------------------+-----------+----------+----------------------------------------
--  id           | text                     |           | not null | generate_typed_uuid('rsnpagevq'::text)
--  rsn_page_id  | text                     |           |          | 
--  created_date | timestamp with time zone |           | not null | now()
--  updated_date | timestamp with time zone |           | not null | now()
--  created_by   | text                     |           |          | 
--  updated_by   | text                     |           |          | 
-- Check constraints:
--     "rsn_page_vec_queue__id__check_prefix" CHECK (is_valid_typed_uuid('rsnpagevq'::text, id::typed_uuid))
-- Policies:
--     POLICY "rsn_page_vec_queue DELETE" FOR DELETE
--       USING (true)
--     POLICY "rsn_page_vec_queue INSERT" FOR INSERT
--       WITH CHECK (true)
--     POLICY "rsn_page_vec_queue SELECT" FOR SELECT
--       USING (true)
--     POLICY "rsn_page_vec_queue UPDATE" FOR UPDATE
--       USING (true)
-- Triggers:
--     run_tgr_apply_audit BEFORE INSERT OR UPDATE ON rsn_page_vec_queue FOR EACH ROW EXECUTE FUNCTION tgr_apply_audit()
-- 
-- 

------------------------------
-- END: TABLE DESCRIPTION (TABLE: public.rsn_page_vec_queue)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (TABLE: public.rsn_page_vec_queue)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: rsn_page_vec_queue; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rsn_page_vec_queue (
    id text DEFAULT public.generate_typed_uuid('rsnpagevq'::text) NOT NULL,
    rsn_page_id text,
    created_date timestamp with time zone DEFAULT now() NOT NULL,
    updated_date timestamp with time zone DEFAULT now() NOT NULL,
    created_by text,
    updated_by text,
    CONSTRAINT rsn_page_vec_queue__id__check_prefix CHECK (public.is_valid_typed_uuid('rsnpagevq'::text, (id)::public.typed_uuid))
);


ALTER TABLE public.rsn_page_vec_queue OWNER TO postgres;

--
-- Name: TABLE rsn_page_vec_queue; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.rsn_page_vec_queue IS 'A queue of rsn pages to be vectorized.';


--
-- Name: rsn_page_vec_queue run_tgr_apply_audit; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER run_tgr_apply_audit BEFORE INSERT OR UPDATE ON public.rsn_page_vec_queue FOR EACH ROW EXECUTE FUNCTION public.tgr_apply_audit();


--
-- Name: rsn_page_vec_queue; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.rsn_page_vec_queue ENABLE ROW LEVEL SECURITY;

--
-- Name: rsn_page_vec_queue rsn_page_vec_queue DELETE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "rsn_page_vec_queue DELETE" ON public.rsn_page_vec_queue FOR DELETE USING (true);


--
-- Name: rsn_page_vec_queue rsn_page_vec_queue INSERT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "rsn_page_vec_queue INSERT" ON public.rsn_page_vec_queue FOR INSERT WITH CHECK (true);


--
-- Name: rsn_page_vec_queue rsn_page_vec_queue SELECT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "rsn_page_vec_queue SELECT" ON public.rsn_page_vec_queue FOR SELECT USING (true);


--
-- Name: rsn_page_vec_queue rsn_page_vec_queue UPDATE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "rsn_page_vec_queue UPDATE" ON public.rsn_page_vec_queue FOR UPDATE USING (true);


--
-- Name: TABLE rsn_page_vec_queue; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.rsn_page_vec_queue TO anon;
GRANT ALL ON TABLE public.rsn_page_vec_queue TO authenticated;
GRANT ALL ON TABLE public.rsn_page_vec_queue TO service_role;


--
-- PostgreSQL database dump complete
--



------------------------------
-- END: PG_DUMP RESULT (TABLE: public.rsn_page_vec_queue)
---------------------------------------------------------------------------

