---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Table: public.stripe_products

---------------------------------------------------------------------------
-- BEGIN: TABLE DESCRIPTION (TABLE: public.stripe_products)
------------------------------
--                         Table "public.stripe_products"
--     Column     |            Type             | Collation | Nullable | Default 
-- ---------------+-----------------------------+-----------+----------+---------
--  id            | text                        |           | not null | 
--  name          | text                        |           |          | 
--  active        | boolean                     |           |          | 
--  default_price | text                        |           |          | 
--  description   | text                        |           |          | 
--  created       | timestamp without time zone |           |          | 
--  updated       | timestamp without time zone |           |          | 
--  attrs         | jsonb                       |           |          | 
-- Indexes:
--     "stripe_products_pkey" PRIMARY KEY, btree (id)
-- Policies:
--     POLICY "stripe_products DELETE" FOR DELETE
--       USING ((auth.role() = 'service_role'::text))
--     POLICY "stripe_products INSERT" FOR INSERT
--       WITH CHECK ((auth.role() = 'service_role'::text))
--     POLICY "stripe_products SELECT" FOR SELECT
--       USING (true)
--     POLICY "stripe_products UPDATE" FOR UPDATE
--       USING ((auth.role() = 'service_role'::text))
-- 
-- 

------------------------------
-- END: TABLE DESCRIPTION (TABLE: public.stripe_products)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (TABLE: public.stripe_products)
------------------------------
--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: stripe_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stripe_products (
    id text NOT NULL,
    name text,
    active boolean,
    default_price text,
    description text,
    created timestamp without time zone,
    updated timestamp without time zone,
    attrs jsonb
);


ALTER TABLE public.stripe_products OWNER TO postgres;

--
-- Name: stripe_products stripe_products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stripe_products
    ADD CONSTRAINT stripe_products_pkey PRIMARY KEY (id);


--
-- Name: stripe_products; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.stripe_products ENABLE ROW LEVEL SECURITY;

--
-- Name: stripe_products stripe_products DELETE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "stripe_products DELETE" ON public.stripe_products FOR DELETE USING ((auth.role() = 'service_role'::text));


--
-- Name: stripe_products stripe_products INSERT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "stripe_products INSERT" ON public.stripe_products FOR INSERT WITH CHECK ((auth.role() = 'service_role'::text));


--
-- Name: stripe_products stripe_products SELECT; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "stripe_products SELECT" ON public.stripe_products FOR SELECT USING (true);


--
-- Name: stripe_products stripe_products UPDATE; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "stripe_products UPDATE" ON public.stripe_products FOR UPDATE USING ((auth.role() = 'service_role'::text));


--
-- Name: TABLE stripe_products; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.stripe_products TO anon;
GRANT ALL ON TABLE public.stripe_products TO authenticated;
GRANT ALL ON TABLE public.stripe_products TO service_role;


--
-- PostgreSQL database dump complete
--



------------------------------
-- END: PG_DUMP RESULT (TABLE: public.stripe_products)
---------------------------------------------------------------------------

