---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public._alike

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public._alike)
------------------------------
CREATE OR REPLACE FUNCTION public._alike(boolean, anyelement, text, text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    result ALIAS FOR $1;
    got    ALIAS FOR $2;
    rx     ALIAS FOR $3;
    descr  ALIAS FOR $4;
    output TEXT;
BEGIN
    output := ok( result, descr );
    RETURN output || CASE result WHEN TRUE THEN '' ELSE E'\n' || diag(
           '                  ' || COALESCE( quote_literal(got), 'NULL' ) ||
       E'\n   doesn''t match: ' || COALESCE( quote_literal(rx), 'NULL' )
    ) END;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public._alike)
---------------------------------------------------------------------------
