---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public._expand_context

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public._expand_context)
------------------------------
CREATE OR REPLACE FUNCTION public._expand_context(character)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
   SELECT CASE $1
          WHEN 'i' THEN 'implicit'
          WHEN 'a' THEN 'assignment'
          WHEN 'e' THEN 'explicit'
          ELSE          'unknown' END
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public._expand_context)
---------------------------------------------------------------------------
