---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public._expand_on

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public._expand_on)
------------------------------
CREATE OR REPLACE FUNCTION public._expand_on(character)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
   SELECT CASE $1
          WHEN '1' THEN 'SELECT'
          WHEN '2' THEN 'UPDATE'
          WHEN '3' THEN 'INSERT'
          WHEN '4' THEN 'DELETE'
          ELSE          'UNKNOWN' END
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public._expand_on)
---------------------------------------------------------------------------
