---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public._get_tablespaceprivs

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public._get_tablespaceprivs)
------------------------------
CREATE OR REPLACE FUNCTION public._get_tablespaceprivs(name, text)
 RETURNS text[]
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF pg_catalog.has_tablespace_privilege($1, $2, 'CREATE') THEN
        RETURN '{CREATE}';
    ELSE
        RETURN '{}';
    END IF;
EXCEPTION WHEN undefined_object THEN
    -- Same error code for unknown user or tablespace. So figure out which.
    RETURN CASE WHEN SQLERRM LIKE '%' || $1 || '%' THEN
        '{undefined_role}'
    ELSE
        '{undefined_tablespace}'
    END;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public._get_tablespaceprivs)
---------------------------------------------------------------------------
