---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public._get_language_owner

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public._get_language_owner)
------------------------------
CREATE OR REPLACE FUNCTION public._get_language_owner(name)
 RETURNS name
 LANGUAGE sql
AS $function$
    SELECT pg_catalog.pg_get_userbyid(lanowner)
      FROM pg_catalog.pg_language
     WHERE lanname = $1;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public._get_language_owner)
---------------------------------------------------------------------------
