---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public._pg_sv_column_array

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public._pg_sv_column_array)
------------------------------
CREATE OR REPLACE FUNCTION public._pg_sv_column_array(oid, smallint[])
 RETURNS name[]
 LANGUAGE sql
 STABLE
AS $function$
    SELECT ARRAY(
        SELECT a.attname
          FROM pg_catalog.pg_attribute a
          JOIN generate_series(1, array_upper($2, 1)) s(i) ON a.attnum = $2[i]
         WHERE attrelid = $1
         ORDER BY i
    )
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public._pg_sv_column_array)
---------------------------------------------------------------------------
