---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public._pg_sv_type_array

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public._pg_sv_type_array)
------------------------------
CREATE OR REPLACE FUNCTION public._pg_sv_type_array(oid[])
 RETURNS name[]
 LANGUAGE sql
 STABLE
AS $function$
    SELECT ARRAY(
        SELECT t.typname
          FROM pg_catalog.pg_type t
          JOIN generate_series(1, array_upper($1, 1)) s(i) ON t.oid = $1[i]
         ORDER BY i
    )
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public._pg_sv_type_array)
---------------------------------------------------------------------------
