---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public._refine_vol

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public._refine_vol)
------------------------------
CREATE OR REPLACE FUNCTION public._refine_vol(text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
    SELECT _expand_vol(substring(LOWER($1) FROM 1 FOR 1)::char);
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public._refine_vol)
---------------------------------------------------------------------------
