---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public._tlike

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public._tlike)
------------------------------
CREATE OR REPLACE FUNCTION public._tlike(boolean, text, text, text)
 RETURNS text
 LANGUAGE sql
AS $function$
    SELECT ok( $1, $4 ) || CASE WHEN $1 THEN '' ELSE E'\n' || diag(
           '   error message: ' || COALESCE( quote_literal($2), 'NULL' ) ||
       E'\n   doesn''t match: ' || COALESCE( quote_literal($3), 'NULL' )
    ) END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public._tlike)
---------------------------------------------------------------------------
