---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.add_skill_xp

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.add_skill_xp)
------------------------------
CREATE OR REPLACE FUNCTION public.add_skill_xp(user_id text, skill_id text, xp_amount integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
declare
    last_reset timestamp with time zone;
    user_timezone text;
begin
    -- Get user's timezone
    select timezone into user_timezone
    from public.rsn_user
    where id = user_id;

    -- Get or create user_skill_sysdata record
    insert into public.user_skill_sysdata (rsn_user, skill)
    values (user_id::public.typed_uuid, skill_id::public.typed_uuid)
    on conflict (rsn_user, skill) do nothing;

    -- Check if we need to reset daily XP based on user's timezone
    select last_daily_reset into last_reset
    from public.user_skill_sysdata
    where rsn_user = user_id::public.typed_uuid and skill = skill_id::public.typed_uuid;

    if (last_reset AT TIME ZONE COALESCE(user_timezone, 'UTC'))::date < 
       (current_timestamp AT TIME ZONE COALESCE(user_timezone, 'UTC'))::date then
        -- Reset daily XP if it's a new day in user's timezone
        update public.user_skill_sysdata
        set daily_xp = xp_amount,
            last_daily_reset = current_timestamp,
            total_xp = total_xp + xp_amount
        where rsn_user = user_id::public.typed_uuid and skill = skill_id::public.typed_uuid;
    else
        -- Add XP to both daily and total
        update public.user_skill_sysdata
        set daily_xp = daily_xp + xp_amount,
            total_xp = total_xp + xp_amount
        where rsn_user = user_id::public.typed_uuid and skill = skill_id::public.typed_uuid;
    end if;
end;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.add_skill_xp)
---------------------------------------------------------------------------
