---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.bytea_to_text

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.bytea_to_text)
------------------------------
CREATE OR REPLACE FUNCTION public.bytea_to_text(data bytea)
 RETURNS text
 LANGUAGE c
 IMMUTABLE STRICT
AS '$libdir/http', $function$bytea_to_text$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.bytea_to_text)
---------------------------------------------------------------------------
