---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.create_page_from_snip

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.create_page_from_snip)
------------------------------
CREATE OR REPLACE FUNCTION public.create_page_from_snip()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.page_id IS NULL AND NEW.text_content IS NOT NULL AND NEW.extraction_state = 'success' THEN
    -- Insert and select
    INSERT INTO rsn_page (_name, body) VALUES (NEW._name, NEW.text_content) RETURNING id INTO NEW.page_id;
  END IF;
  RETURN NEW;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.create_page_from_snip)
---------------------------------------------------------------------------
