---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.cur_user_stripe_customer_id

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.cur_user_stripe_customer_id)
------------------------------
CREATE OR REPLACE FUNCTION public.cur_user_stripe_customer_id(mock text DEFAULT NULL::text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
DECLARE
    stripe_id_ret text;
BEGIN
    SELECT id 
        FROM stripe_customers
        WHERE attrs->>'rsnUserId' = public.current_rsn_user_id()
        INTO stripe_id_ret;

    RETURN stripe_id_ret;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.cur_user_stripe_customer_id)
---------------------------------------------------------------------------
