---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.email_for_rsn_user

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.email_for_rsn_user)
------------------------------
CREATE OR REPLACE FUNCTION public.email_for_rsn_user(rsn_user_id text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN (SELECT auth_email FROM rsn_user WHERE id = rsn_user_id);
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.email_for_rsn_user)
---------------------------------------------------------------------------
