---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.emails_match

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.emails_match)
------------------------------
CREATE OR REPLACE FUNCTION public.emails_match(first_email text, second_email text)
 RETURNS boolean
 LANGUAGE plpgsql
 STABLE
AS $function$
	begin
		return trim(both from first_email) ilike trim(both from second_email);
	end;        
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.emails_match)
---------------------------------------------------------------------------
