---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.env_name

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.env_name)
------------------------------
CREATE OR REPLACE FUNCTION public.env_name()
 RETURNS text
 LANGUAGE plpgsql
AS $function$
    begin
        return 'LOCAL';
    end;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.env_name)
---------------------------------------------------------------------------
