---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.f_raise

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.f_raise)
------------------------------
CREATE OR REPLACE FUNCTION public.f_raise(text)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
   RAISE EXCEPTION '%', $1;
END
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.f_raise)
---------------------------------------------------------------------------
