---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.generate_display_name

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.generate_display_name)
------------------------------
CREATE OR REPLACE FUNCTION public.generate_display_name(given_name text, family_name text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- If both names are null/empty, return null
    IF (given_name IS NULL OR given_name = '') AND (family_name IS NULL OR family_name = '') THEN
        RETURN NULL;
    -- If only given_name exists
    ELSIF family_name IS NULL OR family_name = '' THEN
        RETURN given_name;
    -- If only family_name exists
    ELSIF given_name IS NULL OR given_name = '' THEN
        RETURN family_name;
    -- If both exist, combine them
    ELSE
        RETURN given_name || ' ' || family_name;
    END IF;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.generate_display_name)
---------------------------------------------------------------------------
