---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.generate_typed_uuid

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.generate_typed_uuid)
------------------------------
CREATE OR REPLACE FUNCTION public.generate_typed_uuid(type_prefix text)
 RETURNS text
 LANGUAGE plpgsql
AS $function$    
    BEGIN
        IF type_prefix IS NULL THEN
            RAISE EXCEPTION 'generate_typed_uuid must have a type_prefix passed to it.';
        ELSE
            IF strpos(type_prefix, '_') = 0 THEN  
                RETURN type_prefix || '_' || extensions.uuid_generate_v4();
            ELSE
                RAISE EXCEPTION 'generate_typed_uuid must have a type_prefix passed to it that does not contain an underscore. Got this: %', type_prefix;
            END IF;
        END IF;     
    END;                  
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.generate_typed_uuid)
---------------------------------------------------------------------------
