---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.get_total_user_xp

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.get_total_user_xp)
------------------------------
CREATE OR REPLACE FUNCTION public.get_total_user_xp(user_id text)
 RETURNS TABLE(total_xp bigint, daily_xp bigint)
 LANGUAGE plpgsql
AS $function$
begin
    return query
    select sum(usd.total_xp)::bigint as total_xp,
           sum(usd.daily_xp)::bigint as daily_xp
    from public.user_skill_sysdata usd
    where usd.rsn_user = user_id::public.typed_uuid;
end;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.get_total_user_xp)
---------------------------------------------------------------------------
