---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.get_tablename_from_abbreviation

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.get_tablename_from_abbreviation)
------------------------------
CREATE OR REPLACE FUNCTION public.get_tablename_from_abbreviation(input_abbreviation text)
 RETURNS text
 LANGUAGE plpgsql
 STABLE
AS $function$
DECLARE
    _tablename text;
BEGIN
    SELECT tablename INTO _tablename
        FROM public.rsncore_table_abbreviations
        WHERE abbreviation = input_abbreviation;
    RETURN _tablename;
END
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.get_tablename_from_abbreviation)
---------------------------------------------------------------------------
