---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.get_or_create_notification_subscription

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.get_or_create_notification_subscription)
------------------------------
CREATE OR REPLACE FUNCTION public.get_or_create_notification_subscription(p_user_id text)
 RETURNS SETOF notification_subscription
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    current_user_id text;
BEGIN
    -- Get the current user ID
    current_user_id := (public.current_rsn_user_id())::text;
    
    -- Check if the provided user ID matches the current user ID
    IF p_user_id != current_user_id THEN
        RAISE EXCEPTION 'You can only manage notification subscriptions for yourself';
    END IF;
    
    -- Try to find existing subscription
    RETURN QUERY
    SELECT * FROM notification_subscription
    WHERE rsn_user_id = p_user_id;
    
    -- If no rows returned, create a new subscription
    IF NOT FOUND THEN
        RETURN QUERY
        INSERT INTO notification_subscription (rsn_user_id, created_by, updated_by)
        VALUES (p_user_id, p_user_id, p_user_id)
        RETURNING *;
    END IF;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.get_or_create_notification_subscription)
---------------------------------------------------------------------------
