---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.get_child_pages

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.get_child_pages)
------------------------------
CREATE OR REPLACE FUNCTION public.get_child_pages(parent_page_ids text[])
 RETURNS TABLE(id text, _name text, metadata jsonb, body text, parent text, body_length integer, body_sha_256 text, created_date timestamp with time zone, updated_date timestamp with time zone, created_by text, updated_by text)
 LANGUAGE plpgsql
AS $function$ #variable_conflict use_variable
BEGIN RETURN QUERY
    WITH RECURSIVE child_pages AS (
        SELECT rsn_page.*
            FROM rsn_page
            WHERE rsn_page.id = ANY(parent_page_ids)

        UNION ALL

        SELECT rsn_page.*
        FROM rsn_page
        INNER JOIN child_pages ON rsn_page.parent = child_pages.id
    )
    SELECT child_pages.id, child_pages._name, child_pages.metadata, child_pages.body, child_pages.parent, 
           child_pages.body_length, child_pages.body_sha_256, child_pages.created_date, 
           child_pages.updated_date, child_pages.created_by, child_pages.updated_by
    FROM child_pages;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.get_child_pages)
---------------------------------------------------------------------------
