---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.get_skill_pages

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.get_skill_pages)
------------------------------
CREATE OR REPLACE FUNCTION public.get_skill_pages(skillid text, parentskillids text[] DEFAULT NULL::text[])
 RETURNS TABLE(id text, skill_id text, rsn_page_id text, page_id text, page_name text, page_body text)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    WITH skill_pages AS (
        SELECT sp.id, sp.skill_id, sp.rsn_page_id
        FROM skill_page sp
        WHERE sp.skill_id = skillId
        OR (parentSkillIds IS NOT NULL AND sp.skill_id = ANY(parentSkillIds))
    )
    SELECT sp.id, sp.skill_id, sp.rsn_page_id, rp.id, rp._name, rp.body
    FROM skill_pages sp
    JOIN rsn_page rp ON sp.rsn_page_id = rp.id;
END; $function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.get_skill_pages)
---------------------------------------------------------------------------
