---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.immutable_array_to_string

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.immutable_array_to_string)
------------------------------
CREATE OR REPLACE FUNCTION public.immutable_array_to_string(arr anyarray, delimiter text)
 RETURNS text
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
DECLARE
    str text := '';
    elem text;
BEGIN
    IF arr IS NULL THEN
        RETURN NULL;
    END IF;

    FOR i IN array_lower(arr, 1)..array_upper(arr, 1) LOOP
        elem := arr[i]::text;
        IF i = array_lower(arr, 1) THEN
            str := elem;
        ELSE
            str := str || delimiter || elem;
        END IF;
    END LOOP;
    RETURN str;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.immutable_array_to_string)
---------------------------------------------------------------------------
