---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.is_base_access_level

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.is_base_access_level)
------------------------------
CREATE OR REPLACE FUNCTION public.is_base_access_level(_entity_type text, _access_level text)
 RETURNS boolean
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
    BEGIN 
        RETURN ( _access_level ILIKE 'OWNER' OR 
                _access_level ILIKE 'ADMIN' OR 
                _access_level ILIKE 'EDITOR' OR
                _access_level ILIKE 'VIEWER' OR
                _access_level ILIKE 'COMMENTOR' OR
                _access_level ILIKE 'GUEST'
        ); 
    END; 
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.is_base_access_level)
---------------------------------------------------------------------------
