---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.is_valid_typed_uuid

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.is_valid_typed_uuid)
------------------------------
CREATE OR REPLACE FUNCTION public.is_valid_typed_uuid(type_prefix text, to_test typed_uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$	
	BEGIN
        IF split_part(to_test,'_', 1) <> type_prefix THEN
            return false;
        ELSE
            return true;
        END IF;  
	END;                  
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.is_valid_typed_uuid)
---------------------------------------------------------------------------
