---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.lesson_activity_reorder

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.lesson_activity_reorder)
------------------------------
CREATE OR REPLACE FUNCTION public.lesson_activity_reorder(p_lesson_activity_id text, p_new_position double precision)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_lesson_id TEXT;
    v_current_position FLOAT;
    v_next_position FLOAT;
    v_current_user TEXT;
BEGIN
    v_current_user := public.current_rsn_user_id();

    -- Get the current position and lesson
    SELECT position, lesson INTO v_current_position, v_lesson_id
    FROM public.lesson_activity
    WHERE id = p_lesson_activity_id;

    IF v_current_position IS NULL THEN
        RAISE EXCEPTION 'Lesson activity not found';
    END IF;

    -- Find the position of the next item
    SELECT position INTO v_next_position
    FROM public.lesson_activity
    WHERE lesson = v_lesson_id 
    AND position > p_new_position
    ORDER BY position ASC
    LIMIT 1;

    -- Calculate the new position
    IF v_next_position IS NULL THEN
        v_next_position := p_new_position + 1;
    ELSE
        v_next_position := (p_new_position + v_next_position) / 2;
    END IF;

    -- Update the position
    UPDATE public.lesson_activity
    SET position = v_next_position,
        updated_by = v_current_user,
        updated_date = now()
    WHERE id = p_lesson_activity_id;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.lesson_activity_reorder)
---------------------------------------------------------------------------
