---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.lesson_activity_remove

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.lesson_activity_remove)
------------------------------
CREATE OR REPLACE FUNCTION public.lesson_activity_remove(p_lesson_activity_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_current_user TEXT;
BEGIN
    v_current_user := public.current_rsn_user_id();
    
    -- Delete the lesson_activity
    DELETE FROM public.lesson_activity
    WHERE id = p_lesson_activity_id;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.lesson_activity_remove)
---------------------------------------------------------------------------
