---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.lesson_activity_add

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.lesson_activity_add)
------------------------------
CREATE OR REPLACE FUNCTION public.lesson_activity_add(p_lesson_id text, p_activity_id text, p_metadata jsonb DEFAULT NULL::jsonb, p_desired_position double precision DEFAULT NULL::double precision)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_new_lesson_activity_id TEXT;
    v_position FLOAT;
    v_max_position FLOAT;
    v_current_user TEXT;
BEGIN
    -- Get current user
    v_current_user := public.current_rsn_user_id();

    -- Determine position
    IF p_desired_position IS NULL THEN
        -- If no position specified, add to end
        SELECT COALESCE(MAX(position), 0) + 1 INTO v_position
        FROM public.lesson_activity
        WHERE lesson = p_lesson_id;
    ELSE
        -- Find the position of the next item
        SELECT position INTO v_max_position
        FROM public.lesson_activity
        WHERE lesson = p_lesson_id AND position > p_desired_position
        ORDER BY position ASC
        LIMIT 1;

        IF v_max_position IS NULL THEN
            v_position := p_desired_position;
        ELSE
            v_position := (p_desired_position + v_max_position) / 2;
        END IF;
    END IF;

    -- Insert the new lesson_activity
    INSERT INTO public.lesson_activity (
        lesson,
        activity,
        metadata,
        position,
        created_by,
        updated_by
    ) VALUES (
        p_lesson_id,
        p_activity_id,
        p_metadata,
        v_position,
        v_current_user,
        v_current_user
    ) RETURNING id INTO v_new_lesson_activity_id;

    RETURN v_new_lesson_activity_id;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.lesson_activity_add)
---------------------------------------------------------------------------
