---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.mark_extraction_as_unnecessary

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.mark_extraction_as_unnecessary)
------------------------------
CREATE OR REPLACE FUNCTION public.mark_extraction_as_unnecessary()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.source_url IS NOT NULL 
    AND (NEW.source_url ~ '^\s*
------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.mark_extraction_as_unnecessary)
---------------------------------------------------------------------------
)
    AND NEW.text_content IS NOT NULL
    AND (NEW.text_content ~ '^\s*
------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.mark_extraction_as_unnecessary)
---------------------------------------------------------------------------
)
  THEN
    NEW.extraction_state := 'unnecessary';
  END IF;
  RETURN NEW;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.mark_extraction_as_unnecessary)
---------------------------------------------------------------------------
