---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.pg_version

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.pg_version)
------------------------------
CREATE OR REPLACE FUNCTION public.pg_version()
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$SELECT current_setting('server_version')$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.pg_version)
---------------------------------------------------------------------------
