---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.pgtap_version

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.pgtap_version)
------------------------------
CREATE OR REPLACE FUNCTION public.pgtap_version()
 RETURNS numeric
 LANGUAGE sql
 IMMUTABLE
AS $function$SELECT 1.2;$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.pgtap_version)
---------------------------------------------------------------------------
