---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.pop_from_podcast_queue

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.pop_from_podcast_queue)
------------------------------
CREATE OR REPLACE FUNCTION public.pop_from_podcast_queue()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_next_podcast_id TEXT;
    v_for_user TEXT;
BEGIN
    -- Start an explicit transaction
    BEGIN
        -- Get the current user
        v_for_user := public.current_rsn_user_id();

        -- Get the next podcast in the queue and delete it
        DELETE FROM public.podcast_queue_item
        WHERE id = (
            SELECT id
            FROM public.podcast_queue_item
            WHERE for_user = v_for_user
            ORDER BY position ASC
            LIMIT 1
            FOR UPDATE SKIP LOCKED
        )
        RETURNING podcast_id INTO v_next_podcast_id;

        -- If we get here without errors, the transaction will be committed
    EXCEPTION
        WHEN OTHERS THEN
            -- If an error occurs, the transaction will be rolled back
            RAISE;
    END;

    RETURN v_next_podcast_id;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.pop_from_podcast_queue)
---------------------------------------------------------------------------
