---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.pop_snips_for_auto_param_update

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.pop_snips_for_auto_param_update)
------------------------------
CREATE OR REPLACE FUNCTION public.pop_snips_for_auto_param_update(num_snips integer)
 RETURNS SETOF snip
 LANGUAGE plpgsql
AS $function$
DECLARE
  snip_record snip;
BEGIN
    -- A Function which will will try to pop of a number of snips (the number Provided as an argument) in one of the following states:
        -- auto_param_update_state = 'pending'
        -- auto_param_update_state = 'failed' AND auto_param_update_attempts < 3
        -- auto_last_updated_date is older than 1 hour AND updated_date is newer than 1 hour
    -- When these are popped off, they will be marked as processing.
    -- This function will be called by an LLM.

    FOR snip_record IN
        SELECT * FROM snip
            WHERE auto_param_update_state = 'pending'
            OR (auto_param_update_state = 'failed' AND auto_param_update_attempts < 3)
            OR (auto_last_updated_date < now() - interval '1 hour' AND updated_date > now() - interval '1 hour')
            LIMIT num_snips
    LOOP
    -- Update and set to processing
    -- Also set the auto_param_update_attempts to 0
        UPDATE snip
            SET auto_param_update_state = 'processing'
            WHERE id = snip_record.id;
            RETURN NEXT snip_record;
    END LOOP;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.pop_snips_for_auto_param_update)
---------------------------------------------------------------------------
