---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.set_default_username

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.set_default_username)
------------------------------
CREATE OR REPLACE FUNCTION public.set_default_username()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
DECLARE
    v_given_name TEXT;
    v_family_name TEXT;
BEGIN
    -- Get user info from rsn_user
    SELECT given_name, family_name
    INTO v_given_name, v_family_name
    FROM rsn_user
    WHERE id = NEW.rsn_user_id;

    -- Set username if it's NULL
    IF NEW.username IS NULL THEN
        NEW.username := generate_username(v_given_name, v_family_name);
    END IF;

    -- Set display_name if it's NULL
    IF NEW.display_name IS NULL THEN
        NEW.display_name := generate_display_name(v_given_name, v_family_name);
    END IF;

    RETURN NEW;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.set_default_username)
---------------------------------------------------------------------------
