---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.simple_auth_check

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.simple_auth_check)
------------------------------
CREATE OR REPLACE FUNCTION public.simple_auth_check(created_by_id text, created_date timestamp without time zone)
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN (
        CASE
            WHEN created_by_id IS NOT NULL AND created_by_id = current_rsn_user_id() THEN
                true
            WHEN created_date > now() - INTERVAL '1 minute' THEN
                true
            ELSE
                false
        END
    );
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.simple_auth_check)
---------------------------------------------------------------------------
