---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.split_full_name

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.split_full_name)
------------------------------
CREATE OR REPLACE FUNCTION public.split_full_name(full_name text)
 RETURNS TABLE(given_name text, family_name text)
 LANGUAGE plpgsql
 IMMUTABLE
AS $function$
BEGIN
    -- Split the full name by whitespace
    -- First part becomes given_name, rest becomes family_name
    RETURN QUERY 
    SELECT 
        (regexp_split_to_array(full_name, '\s+'))[1] as given_name,
        array_to_string((regexp_split_to_array(full_name, '\s+'))[2:], ' ') as family_name;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.split_full_name)
---------------------------------------------------------------------------
