---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.tgr_create_snip_skill

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.tgr_create_snip_skill)
------------------------------
CREATE OR REPLACE FUNCTION public.tgr_create_snip_skill()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF NEW.root_skill IS NULL THEN
        -- Create the skill, saving its id so we can use it
        INSERT INTO skill (_name) VALUES (NEW._name) RETURNING id INTO NEW.root_skill;
    END IF;

    RETURN NEW;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.tgr_create_snip_skill)
---------------------------------------------------------------------------
