---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.tgr_update_snip_skill

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.tgr_update_snip_skill)
------------------------------
CREATE OR REPLACE FUNCTION public.tgr_update_snip_skill()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE skill SET _name = NEW._name WHERE id = NEW.root_skill;

    RETURN NEW;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.tgr_update_snip_skill)
---------------------------------------------------------------------------
