---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.tgr_rsn_page_vec_queue_insert

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.tgr_rsn_page_vec_queue_insert)
------------------------------
CREATE OR REPLACE FUNCTION public.tgr_rsn_page_vec_queue_insert()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- This should be triggered by an INSERT / UPDATE
    -- When a new page is created, or a page is updated, add it to the queue if it does not exist.

    -- Check if the page already exists in the queue
    IF EXISTS (SELECT 1 FROM rsn_page_vec_queue WHERE rsn_page_id = NEW.id) THEN
        RETURN NEW;
    END IF;

    -- IF update, check if the body of the page has changed.
    -- If the body has not changed, then do not add it to the queue.
    IF (TG_OP = 'UPDATE') THEN
        IF (OLD.body = NEW.body) THEN
            RETURN NEW;
        END IF;
    END IF;

    -- Add the rsn_page to the queue
    INSERT INTO rsn_page_vec_queue (rsn_page_id) VALUES (NEW.id);

    RETURN NEW;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.tgr_rsn_page_vec_queue_insert)
---------------------------------------------------------------------------
