---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.update_course_updated_date

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.update_course_updated_date)
------------------------------
CREATE OR REPLACE FUNCTION public.update_course_updated_date()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
    -- For INSERT and UPDATE, use NEW
    if (TG_OP = 'INSERT' OR TG_OP = 'UPDATE') then
        update course
        set updated_date = now()
        where id = NEW.course;
        return NEW;
    -- For DELETE, use OLD since NEW is null
    elsif (TG_OP = 'DELETE') then
        update course
        set updated_date = now()
        where id = OLD.course;
        return OLD;
    end if;
    return NULL;
end;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.update_course_updated_date)
---------------------------------------------------------------------------
