---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.update_body_sha_256

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.update_body_sha_256)
------------------------------
CREATE OR REPLACE FUNCTION public.update_body_sha_256()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    BEGIN
        -- Double backslashes to ensure proper escaping
        NEW.body := replace(NEW.body, '\\', '\\\\');

        -- Convert the text to bytea using UTF8 encoding and compute SHA-256 hash
        NEW.body_sha_256 := encode(digest(convert_to(NEW.body, 'UTF8'), 'sha256'), 'hex');

        RETURN NEW;
    EXCEPTION WHEN OTHERS THEN
        RAISE WARNING 'Failed to update body_sha_256 for record with body: %', NEW.body;
        RETURN NEW;
    END;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.update_body_sha_256)
---------------------------------------------------------------------------
