---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.update_lesson_chapter_order

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.update_lesson_chapter_order)
------------------------------
CREATE OR REPLACE FUNCTION public.update_lesson_chapter_order(lesson_id text, target_order integer)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    current_order integer;
    current_chapter text;
BEGIN
    -- Retrieve current order and chapter for the lesson
    SELECT chapter, chapter_order INTO current_chapter, current_order
    FROM public.lesson
    WHERE id = lesson_id;

    -- Check if the lesson is part of a chapter
    IF current_chapter IS NULL THEN
        RAISE EXCEPTION 'Lesson is not associated with a chapter';
    END IF;

    -- Shift other lessons if necessary
    -- NOTE: We assume that chapters are "dense", i.e., there are no gaps in the order numbers
    -- If there are gaps, the logic will be somewhat superfluous.
    IF target_order < current_order THEN
        -- Moving the lesson up in the order
        UPDATE public.lesson
        SET chapter_order = chapter_order + 1
        WHERE chapter = current_chapter AND
              chapter_order >= target_order AND
              chapter_order < current_order;
    ELSIF target_order > current_order THEN
        -- Moving the lesson down in the order
        UPDATE public.lesson
        SET chapter_order = chapter_order - 1
        WHERE chapter = current_chapter AND
              chapter_order <= target_order AND
              chapter_order > current_order;
    END IF;

    -- Update the order for the target lesson
    UPDATE public.lesson
        SET chapter_order = target_order
        WHERE id = lesson_id;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.update_lesson_chapter_order)
---------------------------------------------------------------------------
