---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.update_resend_synced_on_user_change

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.update_resend_synced_on_user_change)
------------------------------
CREATE OR REPLACE FUNCTION public.update_resend_synced_on_user_change()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  UPDATE email_subscription
  SET resend_synced = FALSE
  WHERE rsn_user_id = NEW.id
    AND (
      OLD.given_name IS DISTINCT FROM NEW.given_name
      OR OLD.family_name IS DISTINCT FROM NEW.family_name
    );
  RETURN NEW;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.update_resend_synced_on_user_change)
---------------------------------------------------------------------------
