---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.validate_skill_module_children_ids

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.validate_skill_module_children_ids)
------------------------------
CREATE OR REPLACE FUNCTION public.validate_skill_module_children_ids(p_children_ids text[])
 RETURNS boolean
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF p_children_ids IS NULL THEN
        RETURN true;
    END IF;

    -- Check each ID in the array
    FOR i IN 1..array_length(p_children_ids, 1) LOOP
        -- Check if ID starts with valid prefix
        IF NOT (p_children_ids[i] LIKE 'sklmod_%' OR p_children_ids[i] LIKE 'skill_%') THEN
            RETURN false;
        END IF;

        -- Check if ID exists in respective table
        IF p_children_ids[i] LIKE 'sklmod_%' THEN
            PERFORM 1 FROM public.skill_module WHERE id = p_children_ids[i];
            IF NOT FOUND THEN
                RETURN false;
            END IF;
        ELSE
            PERFORM 1 FROM public.skill WHERE id = p_children_ids[i];
            IF NOT FOUND THEN
                RETURN false;
            END IF;
        END IF;
    END LOOP;

    RETURN true;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.validate_skill_module_children_ids)
---------------------------------------------------------------------------
