---------------------------------------------------------------------------
-- 
-- ⚠️ DO NOT EDIT THIS FILE!
-- THIS FILE WAS AUTOMATICALLY GENERATED FROM THE CONTENTS OF A CLEANLY-MIGRATED DATABASE.
-- 
-- ℹ️ To change the contents of this file, create a new migration under 'supabase/migrations/'
-- that makes the change you would like to see.
-- 
---------------------------------------------------------------------------
-- Function: public.validate_skill_arrays

---------------------------------------------------------------------------
-- BEGIN: PG_DUMP RESULT (FUNCTION: public.validate_skill_arrays)
------------------------------
CREATE OR REPLACE FUNCTION public.validate_skill_arrays()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    -- Validate reference_ids
    IF NEW.reference_ids IS NOT NULL THEN
        IF EXISTS (
            SELECT 1
            FROM unnest(NEW.reference_ids) AS ref_id
            LEFT JOIN public.reference ON reference.id = ref_id
            WHERE reference.id IS NULL
        ) THEN
            RAISE EXCEPTION 'Invalid reference_id found in reference_ids array';
        END IF;
    END IF;

    -- Validate rsn_vec_ids
    IF NEW.rsn_vec_ids IS NOT NULL THEN
        IF EXISTS (
            SELECT 1
            FROM unnest(NEW.rsn_vec_ids) AS rsn_vec_id
            LEFT JOIN public.rsn_vec ON rsn_vec.id = rsn_vec_id
            WHERE rsn_vec.id IS NULL
        ) THEN
            RAISE EXCEPTION 'Invalid rsn_vec_id found in rsn_vec_ids array';
        END IF;
    END IF;

    RETURN NEW;
END;
$function$



------------------------------
-- END: PG_DUMP RESULT (FUNCTION: public.validate_skill_arrays)
---------------------------------------------------------------------------
